import React from 'react';

const BurnwiseLogoPotraceExact = ({ 
  size = 100, 
  animated = false,
  epicBootup = false 
}) => {
  // MATHEMATICALLY EXACT paths generated by potrace auto-tracing tool
  // This is pixel-perfect conversion from your actual image
  
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 504 495"
      xmlns="http://www.w3.org/2000/svg"
    >
      <defs>
        {/* Epic fire gradient - matches cinematic bootup */}
        <linearGradient id="potraceFireGradient" x1="0%" y1="0%" x2="100%" y2="0%">
          <stop offset="0%" stopColor="#FF4500" />
          <stop offset="40%" stopColor="#FF6B35" />
          <stop offset="70%" stopColor="#FF8C42" />
          <stop offset="100%" stopColor="#FFB000" />
        </linearGradient>
        
        {/* Subtle glow filter */}
        <filter id="potraceGlow">
          <feGaussianBlur stdDeviation="2" result="coloredBlur"/>
          <feMerge>
            <feMergeNode in="coloredBlur"/>
            <feMergeNode in="SourceGraphic"/>
          </feMerge>
        </filter>
      </defs>
      
      {/* EXACT POTRACE-GENERATED PATHS - MATHEMATICALLY PRECISE - INVERTED FOR ACTUAL LOGO SHAPES */}
      <g transform="translate(0,495) scale(0.1,-0.1)">
        {/* Main flame segment */}
        <path 
          d="M2737 4632 c-3 -4 -8 -63 -11 -132 -14 -249 -52 -487 -95 -585 -5
          -11 -21 -53 -37 -94 -65 -170 -236 -386 -615 -776 -153 -158 -236 -248 -293
          -318 -34 -42 -38 -52 -32 -85 10 -66 104 -368 152 -488 25 -64 47 -124 49
          -133 5 -26 37 -104 53 -129 l15 -24 26 33 c14 18 32 45 41 60 61 110 424 667
          580 889 33 47 103 153 157 235 53 83 100 152 105 153 4 2 8 10 8 17 0 7 3 15
          8 17 4 2 20 29 36 62 16 32 35 63 41 70 13 13 95 149 95 158 0 3 29 58 65 122
          36 64 65 123 65 131 0 8 -31 79 -69 157 -37 79 -92 193 -121 253 -29 61 -56
          112 -61 113 -5 2 -9 12 -9 23 0 17 -89 197 -111 225 -5 6 -7 13 -6 15 2 2 -4
          12 -14 21 -10 10 -20 14 -22 10z"
          fill="url(#potraceFireGradient)"
          filter={animated ? "url(#potraceGlow)" : "none"}
          className={animated ? 'potrace-flame-animate-1' : ''}
        />
        
        {/* Second flame segment */}
        <path 
          d="M3146 3272 c-11 -19 -76 -205 -76 -220 0 -8 -13 -42 -29 -76 -16 -33
          -43 -90 -59 -126 -17 -36 -73 -146 -126 -244 -53 -99 -96 -183 -96 -188 0 -4
          -4 -8 -10 -8 -5 0 -9 -3 -8 -7 3 -10 -160 -306 -217 -393 -23 -36 -49 -85 -59
          -110 -10 -25 -28 -65 -42 -89 -13 -24 -23 -46 -21 -47 9 -10 684 547 814 672
          82 78 83 79 73 114 -5 19 -18 96 -30 170 -12 74 -27 169 -35 210 -7 41 -23
          134 -36 205 -22 129 -31 156 -43 137z"
          fill="url(#potraceFireGradient)"
          filter={animated ? "url(#potraceGlow)" : "none"}
          className={animated ? 'potrace-flame-animate-2' : ''}
        />
        
        {/* Third flame segment */}
        <path 
          d="M3545 2476 c-11 -7 -24 -14 -30 -15 -5 -1 -24 -15 -42 -31 -17 -17
          -36 -30 -41 -30 -6 0 -12 -4 -14 -8 -1 -5 -39 -30 -83 -57 -44 -26 -108 -69
          -142 -94 -35 -25 -65 -44 -68 -41 -2 3 -10 -2 -17 -11 -7 -8 -60 -49 -118 -89
          -115 -81 -320 -230 -355 -258 -111 -89 -147 -116 -150 -112 -2 3 -10 -2 -17
          -11 -7 -9 -35 -33 -63 -54 -102 -79 -177 -149 -186 -172 -5 -13 -18 -81 -29
          -151 -30 -177 -29 -170 -35 -237 -3 -33 -10 -61 -15 -63 -5 -2 -7 -9 -4 -16 3
          -7 -7 -66 -22 -132 -47 -213 -48 -224 -36 -236 9 -9 12 -9 12 1 0 15 138 181
          151 181 5 0 9 5 9 11 0 11 7 20 145 169 158 170 381 430 544 633 30 37 58 67
          63 67 4 0 8 6 8 14 0 8 9 21 20 29 11 8 18 16 15 18 -2 3 16 26 41 53 24 27
          44 51 45 55 0 3 29 40 64 81 106 124 385 497 385 514 0 10 -15 7 -35 -8z"
          fill="url(#potraceFireGradient)"
          filter={animated ? "url(#potraceGlow)" : "none"}
          className={animated ? 'potrace-flame-animate-3' : ''}
        />
      </g>
      
      {animated && (
        <style>
          {`
            @keyframes potrace-flame-flicker {
              0%, 100% { 
                transform: translateX(0) scale(1); 
                opacity: 1; 
              }
              25% { 
                transform: translateX(0.2px) scale(1.002); 
                opacity: 0.98; 
              }
              50% { 
                transform: translateX(-0.1px) scale(0.999); 
                opacity: 0.96; 
              }
              75% { 
                transform: translateX(0.3px) scale(1.001); 
                opacity: 0.99; 
              }
            }
            
            .potrace-flame-animate-1 {
              animation: potrace-flame-flicker 3s ease-in-out infinite;
              transform-origin: 273px 350px; /* Center of main flame */
            }
            
            .potrace-flame-animate-2 {
              animation: potrace-flame-flicker 2.5s ease-in-out infinite;
              animation-delay: 0.5s;
              transform-origin: 314px 270px; /* Center of second flame */
            }
            
            .potrace-flame-animate-3 {
              animation: potrace-flame-flicker 3.5s ease-in-out infinite;
              animation-delay: 1s;
              transform-origin: 354px 200px; /* Center of third flame */
            }
          `}
        </style>
      )}
    </svg>
  );
};

export default BurnwiseLogoPotraceExact;